---

image_resource:
  type: docker-image
  source: {repository: ubuntu}

resources:

  - name: dummy_repo_a
    type: git
    source:
      uri: https://github.com/danieljamesrees/dummy_repo_a

jobs:

    - name: manual_trigger
      plan:
        - get: dummy_repo_a
        - task: echo
          config:
            platform: linux
            inputs:
              - name: dummy_repo_a
            run:
              path: sh
              args: 
                - -exc
                - |
                  echo "dummy_repo_a was manually triggered"
