---

resources:

    - name: dummy_repo_a
      type: git
      source:
          branch: master
          password: ((git_password))
          uri: https://github.com/danieljamesrees/dummy_repo_a
          username: danieljamesrees

#    - name: dummy_repo_b
#      type: git
#      source:
#          uri: https://github.com/danieljamesrees/dummy_repo_a

jobs:

    - name: no_trigger
      plan:
          - get: dummy_repo_a
          - task: echo_no_trigger
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                inputs:
                    - name: dummy_repo_a
                run:
                    path: sh
                    args: 
                        - -exc
                        - |
                            echo "dummy_repo_a should not have been triggered"

    - name: manual_trigger
      plan:
          - get: dummy_repo_a
          - task: echo_manual_trigger
            input_mapping: {input_repo: dummy_repo_a}
            output_mapping: {output_repo: dummy_repo_a}
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                    - name: input_repo
                outputs:
                    - name: output_repo
                params:
                    return_code: ((return_code))
                    SECRET_SAUCE: ((ive_got_the_key))
                run:
                    path: input_repo/echo_manual_trigger.sh
            ensure:
                put: dummy_repo_a
                params:
                    repository: dummy_repo_a

    - name: no_put_trigger
      plan:
          - get: dummy_repo_a
          - task: echo_no_put_trigger
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                inputs:
                    - name: dummy_repo_a
                run:
                    path: sh
                    args: 
                        - -exc
                        - |
                            echo "dummy_repo_a should not have been triggered by the previous put - even with return code ((return_code))"

    - name: git_trigger
      plan:
          - get: dummy_repo_a
            trigger: true
          - task: echo_git_trigger
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                inputs:
                    - name: dummy_repo_a
                run:
                  path: sh
                  args:
                      - -exc
                      - |
                          echo "dummy_repo_a was meant to be triggered by a git push in a put, even when the preceding task was terminated with return code ((return_code)), and also in the middle of the pipeline when triggered by a push outside of the pipeline"

    - name: passed_trigger
      plan:
          - get: dummy_repo_a
            passed: [manual_trigger]
            trigger: true # Trigger must be present, even when not triggering from git.
          - task: echo_passed_trigger
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                    - name: dummy_repo_a
                run:
                    path: sh
                    args:
                        - -exc
                        - |
                            echo "dummy_repo_a was meant to be triggered by the manual trigger task, even when terminated early, but only when the return code is ((return_code))"
