---

resources:

    - name: dummy_repo_a
      type: git
      source:
          branch: master
          password: ((git_password))
          uri: https://github.com/danieljamesrees/dummy_repo_a
          username: danieljamesrees

#    - name: dummy_repo_b
#      type: git
#      source:
#          uri: https://github.com/danieljamesrees/dummy_repo_a

jobs:

    - name: no_trigger
      plan:
          - get: dummy_repo_a
          - task: echo
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                inputs:
                    - name: dummy_repo_a
                run:
                    path: sh
                    args: 
                        - -exc
                        - |
                            echo "dummy_repo_a should not have been triggered"

    - name: manual_trigger
      plan:
          - get: dummy_repo_a
          - task: echo
            input_mapping: {input_repo: dummy_repo_a}
            output_mapping: {output_repo: dummy_repo_a}
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                    - name: input_repo
                outputs:
                    - name: output_repo
                run:
                    path: sh
                    args: 
                        - -exc
                        - |
                            echo "dummy_repo_a was manually triggered"
                            apt-get update && apt-get install --yes git
                            git clone input_repo output_repo
                            cd output_repo
                            echo >> README.md
                            echo "manual_trigger running at $(date -R)" >> README.md
                            git config user.name "Dummy"
                            git config user.email "dummy@ci"
                            git add README.md
                            git commit -m "Update date."
                            exit ((return_code))
            ensure:
                put: dummy_repo_a
                params:
                    repository: dummy_repo_a

    - name: no_put_trigger
      plan:
          - get: dummy_repo_a
          - task: echo
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                inputs:
                    - name: dummy_repo_a
                run:
                    path: sh
                    args: 
                        - -exc
                        - |
                            echo "dummy_repo_a should not have been triggered by the previous put - even with return code ((return_code))"

    - name: git_trigger
      plan:
          - get: dummy_repo_a
            trigger: true
          - task: echo
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                inputs:
                    - name: dummy_repo_a
                run:
                  path: sh
                  args:
                      - -exc
                      - |
                          echo "dummy_repo_a was meant to be triggered by a git push in a put, even when the preceding task was terminated with return code ((return_code)), and also in the middle of the pipeline when triggered by a push outside of the pipeline"

    - name: passed_trigger
      plan:
          - get: dummy_repo_a
            passed: [manual_trigger]
          - task: echo
            config:
                platform: linux
                image_resource:
                    type: docker-image
                    source: {repository: ubuntu}
                inputs:
                inputs:
                    - name: dummy_repo_a
                run:
                    path: sh
                    args:
                        - -exc
                            echo "dummy_repo_a was meant to be triggered by the manual trigger task, but only when the return code is ((return_code))"

